"""
Django settings for beingwellapi project.
Generated by 'django-admin startproject' using Django 1.8.2.
For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# python imports
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&+*g!3_ynizde&(6-#hlmz3c2wl_5i*arxn3p-e5+%81c-p0^g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'yumu',
    'yumulogging',
    'registration',
    'rest_framework',
    'multiselectfield',
    'oauth2_provider',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.profiling_middleware.ProfileMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    # 'djangosecure.middleware.SecurityMiddleware',
)

ROOT_URLCONF = 'yumu.urls'

# SECURE_SSL_REDIRECT = False
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# os.environ['HTTPS'] = "on"

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# os.environ['wsgi.url_scheme'] = 'https'
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yumu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yumu',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}
# server
# OAUTH_CLIENT_ID = 'XT08bGg3WSoIz3nSn6XZGH0mXmGndUdtJMhYW68J'
# OAUTH_SECRET_KEY = '1pdVyvoiKUDgPDOV2PicNXJcgWSasB3NZFpMQTmozJK65SOdJwSWj96D0AeVd2CUUY2IkgTombWmxI72UaDcIg00oL4vYaiVAsCg9yAMk0aBSGltSJqIsGXwtNQnqp4Q'
# OAUTH_CLIENT_ID = 'N8NxZIinO4wgbZpceY22q6oOPPNofywezgNjpe8a'
# OAUTH_SECRET_KEY = 'wXYmLBD84UAFp4TsJGs5R82BrC7U2kVowDrKSYneAU8NCVnxaDrbSgGjU0vssX2ACVMws5mfLEbfmxQlGcthRfbBNV1wmit9q2YJbmGukbo0ygXTZwWJuScarWwzAZ9S'

OAUTH_CLIENT_ID = 'X5nL8waVPjMUw63zUOX9EbCEsO8JoHnJ2gXtJHYo'
OAUTH_SECRET_KEY = 'CMGwkoatyIZ20LkGCYeG5Le031uWtWqwDqm6FFTcjLGMWsMZHikNodgpJHGO66QWYfViWCaj7yzlv4kWlRk9Xzm8zFe5s4hEwURNfF9CmCVZzvneS95gdLwr3eFGIort'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CELERY_TIMEZONE = 'UTC'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)

AUTH_USER_MODEL = "registration.AppUser"

AUTHENTICATION_BACKENDS = (
    # 'social_auth.backends.facebook.FacebookBackend',
    'registration.auth_backend.AppUserModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'oauth2_provider.backends.OAuth2Backend',
)

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
    ),

    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # )
}

# smtp connection
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'email-smtp.eu-west-1.amazonaws.com'
EMAIL_HOST_USER = 'AKIAIJXC67DHEP7ROFXQ'
EMAIL_HOST_PASSWORD = 'AiuFIMwqlJaq/6035CicQgog1OQ92wJ5dNJPrOcW7Wnx'
EMAIL_PORT = 465

LOGGING_CONFIG = None
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level':'INFO',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': '/var/www/mysite.log',
            'maxBytes': 1024*1024*5, # 5 MB
            'backupCount': 5,
            'formatter':'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'INFO',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    }
}
